### ISSUE TITLE
License declaration is missing

### ISSUE THREAD

**Issue by jengelh** [homalg-project/CAP_project#105]
Concerning https://github.com/homalg-project/CAP_project/releases/download/CAP-2017.07.25/CAP-2017.07.25.tar.gz as well as http://www.gap-system.org/pub/gap/gap4/tar.bz2/packages/CAP-2017.07.25.tar.bz2 :

The package does not have a declaration of what license applies. Just the name would be enough for my needs, but even that is missing. This makes it impossible to distribute with Linux distributions.
Methods that were tried to find any declaration: locate a file whose name matches /copying/i, locate a file whose name matches /license/, locate a file /readme/ which mentions the word /license/i, locate any non-autogenerated file containing the words /gnu.general/i or /warranty/i.

**Comment by jengelh** [comment]
LinearAlgebraForCAP-2017.07.25 is affected as well.

**Comment by sebasguts** [comment]
Thanks for pointing this out. We will license all the packages under GPL2 or later. Will put this in now, so it should come with the next GAP release. Tarballs will be updated today. If you need a different license for a particular distribution, let us know, but I think this should be sufficient, since it is the same license as most of GAP.
