### ISSUE TITLE
Rename some operations starting with `Is*`

### ISSUE THREAD

**Issue by TKuh** [homalg-project/CAP_project#1080]
The names of the following operations don't really constitute a proper English sentence:

* IsEqualForObjects 
* IsEqualForMorphisms
* IsCongruentForMorphisms
* ...?

Instead of `Is*` a better phrasing is to start with `Are*`.

Is there a major reason / hidden concept why they start with `Is`? If not, these could be deprecated and replaced (suggested by @mohamed-barakat).

**Comment by zickgraf** [comment]
ping @sebastianpos

**Comment by sebastianpos** [comment]
`IsProperty`

is the naming convention in GAP for testing a property of an object. Moreover, I think

`IsEqual( a, b )`

is also pretty standard in computer algebra. The suffix

`ForSomeDataStructure`

was our solution to express the dependency of the property of being equal on some data structure. Maybe

`IsEqual_Objects`

would have been a better solution.

I would at least not deprecate these names, but keep them as alternative names, since as a GAP user I would always look for

`IsProperty`

and not for

`AreProperty.`

**Comment by zickgraf** [comment]
Searching for "IsEqual" and "AreEqual" shows that in general both are used. Julia uses [isequal](https://docs.julialang.org/en/v1/base/base/#Base.isequal). GAP also uses `Is...` for properties on two things, e.g. `IsEqualSet`, `IsIdenticalObj`, `IsSubset`.

I think `IsEqual( a, b )` should be read as "b is equal to a", e.g. analogous to `IsSubset`. So one *can* construct a proper English sentence using "is equal".

All in all I agree with @sebastianpos and think we should keep the current convention.

**Comment by mohamed-barakat** [comment]
I am happy with these explanations and will close the issue. I will modify the convention in `Locales` accordingly.
