### ISSUE TITLE
Asymmetry between Evaluation/CoevaluationMorphism and CoclosedEvaluation/CoevaluationMorphism

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1242]
@TKuh: Could you please check the correctness of the specification/documentation of CoclosedEvaluation/CoevaluationMorphism is correct and its compatibility with your master thesis?

**Comment by TKuh** [comment]
With asymmetry you mean the order in which the objects $a,b$ appear in the specifications?
I.e. the order of the evaluation $$\underline{\mathrm{Hom}}(a,b)\otimes a \rightarrow b$$ is $a,b,a,b$ and the order of the coclosed evaluation $$a \rightarrow \underline{\mathrm{coHom}}(a,b) \otimes b$$ is $a,a,b,b$?
If yes, then this break in symmetry is because we decided to use the $\underline{\mathrm{coHom}}$-notation in the (left) coclosed case: $$\underline{\mathrm{coHom}}(a,b) \coloneqq \underline{\mathrm{Hom}}(b,a)$$ Writing the coclosed evaluation in $\underline{\mathrm{Hom}}$-notation gives
$$a \rightarrow \underline{\mathrm{Hom}}(b,a) \otimes b$$ and the symmetry is back. But I agree, that the $\underline{\mathrm{coHom}}$-notation is confusing exactly because of this. It's also the reason why I  never use it in my thesis. I can add more details if you prefer. All of this is compatible with my thesis.

**Comment by mohamed-barakat** [comment]
Excellent, I just wanted reassurance.
