### ISSUE TITLE
option `FinalizeCategory := false` has no effect on TerminalCategoryWithMultipleObjects

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1594]
```gap
gap> LoadPackage("CAP", false);;
gap> T := TerminalCategoryWithMultipleObjects( : FinalizeCategory := false );;
gap> IsFinalized( T );
true
```

**Comment by mohamed-barakat** [comment]
This bug is caused by https://github.com/homalg-project/CAP_project/pull/1592.

**Comment by zickgraf** [comment]
The actual bug is that `TerminalCategoryWithSingleObject` is not called with `FinalizeCategory := true` here: https://github.com/homalg-project/CAP_project/blob/8ffc32e057167fdb5f4b843b9c9c4ef07956c2ed/CAP/gap/TerminalCategory.gi#L365

Background: With #1592, the `FinalizeCategory := false` is actually "consumed" by the first call to `Finalize`, which in the above example is triggered by https://github.com/homalg-project/CAP_project/blob/8ffc32e057167fdb5f4b843b9c9c4ef07956c2ed/CAP/gap/TerminalCategory.gi#L365

Probably #1592 will uncover many more examples of missing `FinalizeCategory := true`.

**Comment by mohamed-barakat** [comment]
> The actual bug is that `TerminalCategoryWithSingleObject` is not called with `FinalizeCategory := true` here:
> 
> https://github.com/homalg-project/CAP_project/blob/8ffc32e057167fdb5f4b843b9c9c4ef07956c2ed/CAP/gap/TerminalCategory.gi#L365

Excellent.
 
> Background: With #1592, the `FinalizeCategory := false` is actually "consumed" by the first call to `Finalize`, which in the above example is triggered by
> 
> https://github.com/homalg-project/CAP_project/blob/8ffc32e057167fdb5f4b843b9c9c4ef07956c2ed/CAP/gap/TerminalCategory.gi#L365

I see. Thanks for spotting the source of the bug and the explanation.
 
> Probably #1592 will uncover many more examples of missing `FinalizeCategory := true`.

Yes, this would be desirable.
