### ISSUE TITLE
Since 316b8942ebdb354e8a8e208caeb10aad84258fc6 GradedModulePresentationsForCAP does not load FreydCategoriesForCAP

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#1611]
I assume this is intended:

After:
```gap
gap> LoadPackage( "GradedModulePresentationsForCAP", false );
true
gap> IsPackageMarkedForLoading( "FreydCategoriesForCAP", ">= 0" );
false
```

Before:
```gap
gap> LoadPackage( "GradedModulePresentationsForCAP", false );
true
gap> IsPackageMarkedForLoading( "FreydCategoriesForCAP", ">= 0" );
true
```

**Comment by zickgraf** [comment]
Yes, this is intended: FreydCategoriesForCAP was added as a suggested dependency of ModulePresentationsForCAP in db187f9bc0ef363f8922234c1c1d7b1873e34c71 to allow the user to create left/right presentations with "no_precompiled_code := true". But since "no_precompiled_code := true" is a very special feature, I think the suggested dependency was overkill for the average user. Thanks to GAP's package extensions, we can now avoid the suggested dependency and have the following improved workflow:
```
gap> LoadPackage( "ModulePresentationsForCAP", false );;
gap> QQ := HomalgFieldOfRationals( );;
gap> cat := LeftPresentations( QQ : no_precompiled_code );
Error, To get a version of `LeftPresentations` without precompiled code, the package `FreydCategoriesForCAP` is required. [...]
gap> LoadPackage( "FreydCategoriesForCAP", false );;
gap> cat := LeftPresentations( QQ : no_precompiled_code );
Category of left presentations of Q
```

**Comment by mohamed-barakat** [comment]
I see. Since `FreydCategoriesForCAP` installs more CAP operations, the number of installed operations differs significantly, even for the compiled instance,  depending on whether `FreydCategoriesForCAP` is loaded or not.
