### ISSUE TITLE
Declaration of LinearClosureObject as KeyDependentOperation leads to errors.

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/CAP_project#462]
Here is an example:
```
LoadPackage( "FreydCategories" );
ZZ := HomalgRingOfIntegers( );;
ab := LeftPresentations( ZZ );;
compare_func := {alpha,beta} -> Random([true,false]);;
linear_closure := LinearClosure( ZZ, ab, compare_func );;
a := FreeLeftPresentation(1,ZZ);;
b := FreeLeftPresentation(2,ZZ);;
LinearClosureObject( linear_closure, a );
# LinearClosure(<An object in Category of left presentations of Z>)
LinearClosureObject( linear_closure, b );
Error, no method found! For debugging hints type ?Recovery from NoMethodFound
Error, no 1st choice method found for `<' on 
```
I suggest declaring it as operation and installing it as a method with cache.

**Comment by sebastianpos** [comment]
Thank you very much for pointing that out: KeyDependentOperation needs objects that can be compared via `<`, which is why my construction only worked for single object categories.

Now, I decided not to use caches at all, the performance of the tests is still the same. However, maybe we will come back to the question of caching theses objects one day.
