### ISSUE TITLE
Bug in QuiverRows category

### ISSUE THREAD

**Issue by kamalsaleh** [homalg-project/CAP_project#480]
```
LoadPackage( "Bialgebroids" );
QQ := HomalgFieldOfRationals();;
quiver := RightQuiver( "Q(3)[a:1->2,b:1->2,c:2->3]" );;
Av := Vertices( quiver );; 
A := PathAlgebra( QQ, quiver );;
a := BasisPaths( CanonicalBasis( A ) );;
a := List( a, p -> PathAsAlgebraElement( A, p ) );;
zA := Zero( A );;
QRowsA := QuiverRows( A );;
mat := [ [ a[1], zA ], [ zA, a[6] ], [ a[1], zA ] ];;
obj1 := QuiverRowsObject( [ [ Av[1], 1 ], [ Av[2], 1 ], [ Av[1], 1 ] ], QRowsA );;
obj2 := QuiverRowsObject( [ [ Av[1], 1 ], [ Av[3], 1 ] ], QRowsA );;
alpha_1 := UniversalMorphismIntoZeroObject( obj1 );
alpha_2 := UniversalMorphismFromZeroObject( obj2 );
alpha := PreCompose( alpha_1, alpha_2 );
AsListListOfMatrices( alpha );
Error, List Elements: <list>[1] must have an assigned value in
  Add( row, List( mat{intr}, function ( r )
# HomStructure( alpha, alpha );
```

**Comment by kamalsaleh** [comment]
```
IsCongruentForMorphisms( alpha, ZeroMorphism( Source( alpha ), Range( alpha ) ) );
# false
```

**Comment by kamalsaleh** [comment]
This how I locally fixed the issue:
https://github.com/kamalsaleh/CAP_project/commit/ee471007639f85b04dcb260e7d6614abfaa6d66a

The clean fix raises the question whether `[]` should be allowed as a morphism matrix between non-zero objects or not, which may trigger some changes in other methods, such as the morphism constructor or  is-well-defined methods.

**Comment by sebastianpos** [comment]
Thanks for spotting this!
I'm sorry for not writing down the specifications of the data structure in this case.
I think it should be the same as in the case of the additive closure category:
- for objects consisting of summands >=1, MorphismMatrix should be a proper list of lists
- if either source or range has zero summands, the morphism should be given by []

I tried your proposed fix and have the impression that it suffices to make only a change within the `PreCompose` function. The other changes do not yield different results, since they touch only cases in which either the source or the range has no summands. 

If you agree, it would be nice if you provided the PR with the corresponding change.

**Comment by kamalsaleh** [comment]
Of course, I will provide a PR from the same branch.
