### ISSUE TITLE
Supporting empty limits

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#643]
This issue is a new proposal superseding PR #630. The main goal is still the same: handle corner cases like empty limits, e.g.
https://github.com/homalg-project/CAP_project/blob/a3412c12e06db2fd6be86d0e7e372df8b449ddd6/FreydCategoriesForCAP/gap/AdditiveClosure.gi#L951-L955
without if/else statements. This would simplify some implementations which is nice on its own, but my main motivation is: make compiling certain things easier (or even possible) for CompilerForCAP.

### Status quo
Empty limits are already partially supported. For example, one can call `DirectSum` with the category as first argument, which then redirects to `ZeroObject` in the empty case:
https://github.com/homalg-project/CAP_project/blob/a3412c12e06db2fd6be86d0e7e372df8b449ddd6/CAP/gap/UniversalObjects.gi#L339-L353
(note that the second argument of `DirectSumOp` is the first argument of `DirectSum` in this case). This approach has two drawbacks:

1. This is outside of the CAP derivation mechanism, so if `ZeroObject` is not installed, the function call will fail.
2. This just moves the if/else statement to another level, where it is even harder to find for CompilerForCAP.

### Proposal
I propose that we update the specifications and require categories to also handle empty limits. Many existing categories already handle this fine, for example when using `Sum`, which simply returns 0 for the empty list. If needed, we could provide a feature flag to distinguish between the two specifications, e.g. `cat!.supports_empty_limits`, so this could be fully backwards compatible.

Regarding possible implementations:
1. We have to replace method selection objects by their categories. I would propose to pass the category as the first argument to stay compatible with the existing setting for `DirectSum`.
2. Some operations (in particular, universal morphisms) would need to be enhanced to a full specification even in the case of empty limit (e.g. passing the test object as an additional argument).

All of this could be done transparently for the user via suitable convenience functions.

### Further enhancements
We could enhance this further in two directions:
1. Allow to pass the category as the first argument to any operation, regardless of the need for method selection.
2. Also pass the category on to the functions added via `AddX`.

The first point would be for consistency and simplicity (so you would not have to think about if you have to pass the category as first argument or not). The second point would allow us to write code which does not rely on variables in the context of a function but solely on local variables. For example, the empty direct sum would not have to get the category from the context, but could simply use the first argument. Both points together would make it much easier for CompilerForCAP to trace for which category an operation is called (in particular, if one wants to do that without just-in-time execution). But it would possibly clutter the code with lots of category arguments. To get a feeling for this, I have randomly picked some code and have enhanced it with `cat` arguments:
```
AddWithGivenDerivationPairToCAP( ProjectionInFactorOfFiberProduct,
        
  function( cat, diagram, projection_number )
    local D, diagram_of_equalizer, iota;
    
    D := List( diagram, Source );
    
    diagram_of_equalizer := List( [ 1 .. Length( D ) ], i -> ProjectionInFactorOfDirectProduct( cat, D, i ) );
    
    diagram_of_equalizer := List( [ 1 .. Length( D ) ], i -> PreCompose( cat, diagram_of_equalizer[i], diagram[i] ) );
    
    iota := EmbeddingOfEqualizer( cat, diagram_of_equalizer );
    
    return PreCompose( cat, [ IsomorphismFromFiberProductToEqualizerOfDirectProductDiagram( cat, diagram ), iota, ProjectionInFactorOfDirectProduct( cat, D, projection_number ) ] );
    
  end : Description := "ProjectionInFactorOfFiberProduct by composing the embedding of equalizer with the direct product projection" );
```

### Drawbacks
1. Some derivations like deriving `DirectProduct` from `ProjectionInFactorOfDirectProduct` would not work anymore as they require a non-empty list. On the other hand, we could now derive `ZeroObject` as the empty direct sum.
2. We could run into problems with the caching mechanism. But I hope these would not be too dramatic since the caches are created per category anyway, so "empty lists of cells in different categories" should not be a problem.

### Discussion
@sebastianpos and @ everyone interested: I think we should not discuss all of this at once but in several steps. The first step would be: Do you think going in this direction is worthwhile despite the possible drawbacks? Do you have categories where you would love to have empty limits? Or where you would hate having to handle empty limits?

**Comment by sebastianpos** [comment]
I think your proposal is a worthwhile project on its own. I understand your need for more annotation in order to implement the compiler. The question whether I really like to have empty lists is not crucial for this project (I do, for the record) ;-)

So yes, a finite state could be that each basic operation has a category as its first argument (which would also better resemble a type theoretic approach). Whenever possible, there should be convenience functions that infer that first argument. That would ensure that from the user's point of view, nothing has changed from the outside.

**Comment by zickgraf** [comment]
Perfect, then this discussion was much shorter than I expected :D

If we pass around the category explicitly for all operations, I would start with that and get back to supporting empty limits afterwards (as that should then simply be a matter of dropping the method selection argument which will be obsolete anyway).

One remaining detail to discuss:

Instead of passing the category as the first argument (which is not so nice to read and write, I think), @mohamed-barakat has suggested to attach the functions as components to the category so that we can write `cat!.PreCompose( alpha, beta )` instead of `PreCompose( cat, alpha, beta )`.

Using this notation, the example given in the first comment would read
```
AddWithGivenDerivationPairToCAP( ProjectionInFactorOfFiberProduct,
        
  function( cat, diagram, projection_number )
    local D, diagram_of_equalizer, iota;
    
    D := List( diagram, Source );
    
    diagram_of_equalizer := List( [ 1 .. Length( D ) ], i -> cat!.ProjectionInFactorOfDirectProduct( D, i ) );
    
    diagram_of_equalizer := List( [ 1 .. Length( D ) ], i -> cat!.PreCompose( diagram_of_equalizer[i], diagram[i] ) );
    
    iota := cat!.EmbeddingOfEqualizer( diagram_of_equalizer );
    
    return cat!.PreCompose( [ cat!.IsomorphismFromFiberProductToEqualizerOfDirectProductDiagram( diagram ), iota, cat!.ProjectionInFactorOfDirectProduct( D, projection_number ) ] );
    
  end : Description := "ProjectionInFactorOfFiberProduct by composing the embedding of equalizer with the direct product projection" );
```

For testing the performance impact, I have done some benchmarking with
* a simple function `myfunc := x -> x`, which is also installed as `MyOperation`,
* `myobj!.myfunc := myfunc`,
* `myobj!.MyOperation := MyOperation`

and got the following results:
1. 20 million calls of `myfunc(i)`: 1.15 seconds
2. 20 million calls of `MyOperation(i)`: 1.3 seconds
3. 20 million calls of `myobj!.myfunc(i)`: 1.4 seconds
4. 20 million calls of `myobj!.MyOperation(i)`: 1.55 seconds

Notes:
* Cases 3 and 4 heavily depend on the number of components of `myobj`. I have chosen a worst case scenario by using `CAP_INTERNAL_METHOD_NAME_RECORD` as the underlying record for `myobj`, so most categories should have less components as they do not implement every possible operation.
* Case 2 might also depend on how many methods are installed for `MyOperation`.
* We could also get rid of the `!` by installing a suitable method for `\.`, but that would make the overhead even larger (at least 2.2 seconds).
* Of course, when using the compiler this overhead would disappear anyway. But maybe this should not be the standard excuse for writing slow code :D

I'm not sure which option I would prefer, so I'm happy to collect some opinions!

**Comment by sebastianpos** [comment]
Okay, here is my opinion:

I prefer the type theoretic code `PreCompose( cat, alpha, beta )` to the object-oriented code `cat!.PreCompose( alpha, beta )`.

From today's perspective, I judge it as a design mistake that we associated every basic operation to just a single category in CAP.
That makes it impossible to correctly deal with a basic operation like: a tensor product between two different categories.

Take a look at the basic operation `InterpretMorphismFromDistinguishedObjectToHomomorphismStructureAsMorphism`.
Ideally, it already should have two category variables as its context.

So, in order to make your compiler independent of this design mistake, I would really recommend the type theoretic expression.
I would also recommend to put two category variables as the first two arguments of `InterpretMorphismFromDistinguishedObjectToHomomorphismStructureAsMorphism`.

**Comment by mohamed-barakat** [comment]
I see Sebastian's point and like it very much.

When writing category constructors I often face the problem of missing information in the arguments of the function installed by `AddXY`, which I end up grabbing from the scope as (relatively) global variables. I don't like being forced to do this, basically for the following reasons:
* a print of the method is always incomplete
* GAP cannot dispatch the function but has to keep its scope along with the function in memory
* I cannot imagine how an offline compiler could handle this properly

With this experience in mind, I would even suggest going one step further by (not only providing the category as the first argument) but also providing *both* source and the target to every CAP-operation returning a morphism, i.e., not only making the `WithGiven`-operations the standard ones but even enhancing them with both source and target, always. By this, we can get rid of
* the suffix `WithGiven...` and
* the io_type in the method record.

Since the type of morphism is a dependent type this should even be more in-line with providing complete type-theoretic information for input and output.

**Comment by mohamed-barakat** [comment]
I just had a discussion we Fabian and we decided to postpone the discussion about the inclusion of both source and target to a later point. My above comment can be ignored in this issue. We will raise the point later with more context.
