### ISSUE TITLE
Colift -> ColiftAlongEpimorphism in AttributeCategoryForCAP?

### ISSUE THREAD

**Issue by mohamed-barakat** [homalg-project/CAP_project#85]
Is it possible that the `Colift`/`Lift` in `AttributeCategoryForCAP` actually mean `CokernelColift`/`KernelLift` or `ColiftAlongEpimorphism`/`LiftAlongMonomorphism`?

If yes, then also `ActionsForCAP` has to be modified.

**Comment by sebastianpos** [comment]
I enhanced the construction process of an attribute category
with 2 lists in the following commit: 37c7736b63596d633617
`NoInstallList`: name all functions from the underlying category
that shall not be lifted to the category with attributes
`InstallList`: name all non-primitive functions from the underlying category
that shall be lifted to the category with attributes

In the case of the (co)action category, the methods `Lift` and `Colift` 
must not be lifted from the underlying category, since the (co)lifts
may not be compatible with the action. However, `LiftAlongMonomorphism`
and `LiftAlongEpimorphism` shall be compatible with the action, and thus can
be installed using the methods from the underlying category.

In the case of "objects with generators modeled by generalized monos",
no adjustment is needed.

Note that the record component `Lift` and `Colift`of the `structure_record`
that you have to create while the construction of an attribute category
neither refers to the Cap-command `Lift` and `Colift` nor `LiftAlongMonomorphism`
and `LiftAlongEpimorphism`, but simply to the procedure that
enhances the source of a monomorphism/ the range of an epimorphism
by its attribute.

**Comment by mohamed-barakat** [comment]
Thanks.
