### ISSUE TITLE
Test in ModulesOverLocalRingsForCAP does not finish

### ISSUE THREAD

**Issue by zickgraf** [homalg-project/CAP_project#857]
While applying PackageJanitor to more packagesin CAP_project I noticed that line 17 of the test `IntersectionFormula.g` in `ModulesOverLocalRingsForCAP` does not terminate (after some minutes). I have bisected this to 20526caef7fd24bc67cc05c53d9a702ec1e1ff7c, which is a revert but does not contain any information about why the revert was necessary. @sebastianpos Since you are the author of the test and of the revert, could you have a quick look at this? Is there a quick fix, or should we remove/exclude the test?

**Comment by sebastianpos** [comment]
We should exclude the test for now.

Revert: it was necessary since the algorithm for computing the annihilator was mathematically wrong.

At the moment, the algorithm for computing the annihilator is correct but slow. It would be interesting to understand why homalg is able to do the computation of that annihilator, and then adapt CAP's implementation.

**Comment by zickgraf** [comment]
Thanks for the quick reply! I have excluded the test in the PR linked above.

Should we keep this issue open for future investigation, or just close it now?

**Comment by sebastianpos** [comment]
You can close it.
